FROM python:3.10-slim

ARG SKYMINER_API_URL
ARG CHECKPOINT_PATH
ARG MODEL_PATH
ARG NOTEBOOK_PATH
ARG DAGSTER_HOME
ARG GRAPHQL_URL

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libgomp1 \ 
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

# Install Dagster libraries
RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker 

# Add repository code
WORKDIR /opt/dagster/

# Copy repository code to the working directory
COPY ./intelligent_pipeline intelligent_pipeline
COPY ./SkyminerTS-1.0.19-py3-none-any.whl .
COPY ./requirements.txt .

ENV SKYMINER_API_URL=${SKYMINER_API_URL}
ENV CHECKPOINT_PATH=${CHECKPOINT_PATH}
ENV MODEL_PATH=${MODEL_PATH}
ENV NOTEBOOK_PATH=${NOTEBOOK_PATH}
ENV DAGSTER_HOME=${DAGSTER_HOME}
ENV GRAPHQL_URL=${GRAPHQL_URL}

# Install requirements and wheel file
RUN pip install -r requirements.txt 
RUN pip install SkyminerTS-1.0.19-py3-none-any.whl

# Expose port 9090 for gRPC server
EXPOSE 9090

# Run Dagster gRPC server with the correct working directory and module name
CMD ["dagster", "api", "grpc", "--module-name", "intelligent_pipeline", "--host", "0.0.0.0", "--port", "9090"]
