FROM python:3.10-slim

ARG DAGSTER_HOME

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy Dagster instance configuration
ENV DAGSTER_HOME=${DAGSTER_HOME}
ENV DAGSTER_URL = http://localhost:4000
ENV GRAPHQL_URL = http://localhost:4000/graphql

RUN mkdir -p $DAGSTER_HOME
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

# Expose port 4000 for webserver
EXPOSE 4000

WORKDIR $DAGSTER_HOME
